### ISSUE TITLE
Problem when I use "user" in docker-compose.yaml

### ISSUE THREAD

**Issue by simonbcn** [sbondCo/Watcharr#184]
watcharr executed from docker:
```
❯ docker --version
Docker version 24.0.6, build ed223bc820

❯ cat docker-compose.yaml
version: "3"

services:
  watcharr:
    # The :latest tag is used for simplicity, it is recommended
    # to use an actual version, then when updating check the releases for changelogs.
    image: ghcr.io/sbondco/watcharr:latest
    container_name: watcharr
    #restart: always
    #user: 1000:1000
    ports:
      - 3080:3080
    volumes:
      # Contains all of watcharr data (database & cache)
      - ./data:/data
```

If I uncomment the line where I define the `user`, when I execute `docker-compose up` it does not give error but I cannot access `localhost:3080`.
